### ISSUE TITLE
a question about mask rule

### ISSUE THREAD

**Issue by mumuorMUMU** [mengchengTang/DRL-Energy-optimal-Routing-for-Electric-Vehicles#3]
Excuse me, I'd like to ask if there will be a situation where all actions are not feasible according to the mask rule mentioned on this paper. Looking forward to your answers! Thanks!

**Comment by mengchengTang** [comment]
When all actions are infeasible, the depot node will be opened. And when all instances within a batch can only choose the depot, the round ends.

**Comment by mumuorMUMU** [comment]
Thank you for your reply. Based on your answer, can it be understood that this round of exploration failed? So will this happen during the inference phase of the model? Looking forward to your reply！

**Comment by mengchengTang** [comment]
EVRP instances are meticulously designed to prevent exploration failures, meaning situations where all points are masked do not occur. In my previous response, vehicles only choose the depot because all customer points have been serviced, and there are other instances within the same batch that have not completed exploration. Thus, this instance waits for other instances to finish exploring by continuously selecting the depot node.

**Comment by mumuorMUMU** [comment]
You answered my doubts. Thank you very much for your reply！
